# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/daniec/Projects/cpptools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/daniec/Projects/cpptools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CLion.app/Contents/bin/cmake/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniec/Projects/cpptools/CMakeFiles /Users/daniec/Projects/cpptools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniec/Projects/cpptools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named trees_test

# Build rule for target.
trees_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trees_test
.PHONY : trees_test

# fast build rule for target.
trees_test/fast:
	$(MAKE) -f CMakeFiles/trees_test.dir/build.make CMakeFiles/trees_test.dir/build
.PHONY : trees_test/fast

#=============================================================================
# Target rules for targets named linkedlist_test

# Build rule for target.
linkedlist_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linkedlist_test
.PHONY : linkedlist_test

# fast build rule for target.
linkedlist_test/fast:
	$(MAKE) -f CMakeFiles/linkedlist_test.dir/build.make CMakeFiles/linkedlist_test.dir/build
.PHONY : linkedlist_test/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named test_all

# Build rule for target.
test_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_all
.PHONY : test_all

# fast build rule for target.
test_all/fast:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/build
.PHONY : test_all/fast

#=============================================================================
# Target rules for targets named sort_test

# Build rule for target.
sort_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sort_test
.PHONY : sort_test

# fast build rule for target.
sort_test/fast:
	$(MAKE) -f CMakeFiles/sort_test.dir/build.make CMakeFiles/sort_test.dir/build
.PHONY : sort_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f build/cmake/googletest/googlemock/CMakeFiles/gmock.dir/build.make build/cmake/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f build/cmake/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make build/cmake/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f build/cmake/googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make build/cmake/googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f build/cmake/googletest/googlemock/gtest/CMakeFiles/gtest.dir/build.make build/cmake/googletest/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cc.s
.PHONY : src/main.cc.s

test/linkedlist/linkedlist_test.o: test/linkedlist/linkedlist_test.cc.o

.PHONY : test/linkedlist/linkedlist_test.o

# target to build an object file
test/linkedlist/linkedlist_test.cc.o:
	$(MAKE) -f CMakeFiles/linkedlist_test.dir/build.make CMakeFiles/linkedlist_test.dir/test/linkedlist/linkedlist_test.cc.o
.PHONY : test/linkedlist/linkedlist_test.cc.o

test/linkedlist/linkedlist_test.i: test/linkedlist/linkedlist_test.cc.i

.PHONY : test/linkedlist/linkedlist_test.i

# target to preprocess a source file
test/linkedlist/linkedlist_test.cc.i:
	$(MAKE) -f CMakeFiles/linkedlist_test.dir/build.make CMakeFiles/linkedlist_test.dir/test/linkedlist/linkedlist_test.cc.i
.PHONY : test/linkedlist/linkedlist_test.cc.i

test/linkedlist/linkedlist_test.s: test/linkedlist/linkedlist_test.cc.s

.PHONY : test/linkedlist/linkedlist_test.s

# target to generate assembly for a file
test/linkedlist/linkedlist_test.cc.s:
	$(MAKE) -f CMakeFiles/linkedlist_test.dir/build.make CMakeFiles/linkedlist_test.dir/test/linkedlist/linkedlist_test.cc.s
.PHONY : test/linkedlist/linkedlist_test.cc.s

test/sort/sort_test.o: test/sort/sort_test.cc.o

.PHONY : test/sort/sort_test.o

# target to build an object file
test/sort/sort_test.cc.o:
	$(MAKE) -f CMakeFiles/sort_test.dir/build.make CMakeFiles/sort_test.dir/test/sort/sort_test.cc.o
.PHONY : test/sort/sort_test.cc.o

test/sort/sort_test.i: test/sort/sort_test.cc.i

.PHONY : test/sort/sort_test.i

# target to preprocess a source file
test/sort/sort_test.cc.i:
	$(MAKE) -f CMakeFiles/sort_test.dir/build.make CMakeFiles/sort_test.dir/test/sort/sort_test.cc.i
.PHONY : test/sort/sort_test.cc.i

test/sort/sort_test.s: test/sort/sort_test.cc.s

.PHONY : test/sort/sort_test.s

# target to generate assembly for a file
test/sort/sort_test.cc.s:
	$(MAKE) -f CMakeFiles/sort_test.dir/build.make CMakeFiles/sort_test.dir/test/sort/sort_test.cc.s
.PHONY : test/sort/sort_test.cc.s

test/test_all.o: test/test_all.cc.o

.PHONY : test/test_all.o

# target to build an object file
test/test_all.cc.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/test/test_all.cc.o
.PHONY : test/test_all.cc.o

test/test_all.i: test/test_all.cc.i

.PHONY : test/test_all.i

# target to preprocess a source file
test/test_all.cc.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/test/test_all.cc.i
.PHONY : test/test_all.cc.i

test/test_all.s: test/test_all.cc.s

.PHONY : test/test_all.s

# target to generate assembly for a file
test/test_all.cc.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/test/test_all.cc.s
.PHONY : test/test_all.cc.s

test/trees/trees_test.o: test/trees/trees_test.cc.o

.PHONY : test/trees/trees_test.o

# target to build an object file
test/trees/trees_test.cc.o:
	$(MAKE) -f CMakeFiles/trees_test.dir/build.make CMakeFiles/trees_test.dir/test/trees/trees_test.cc.o
.PHONY : test/trees/trees_test.cc.o

test/trees/trees_test.i: test/trees/trees_test.cc.i

.PHONY : test/trees/trees_test.i

# target to preprocess a source file
test/trees/trees_test.cc.i:
	$(MAKE) -f CMakeFiles/trees_test.dir/build.make CMakeFiles/trees_test.dir/test/trees/trees_test.cc.i
.PHONY : test/trees/trees_test.cc.i

test/trees/trees_test.s: test/trees/trees_test.cc.s

.PHONY : test/trees/trees_test.s

# target to generate assembly for a file
test/trees/trees_test.cc.s:
	$(MAKE) -f CMakeFiles/trees_test.dir/build.make CMakeFiles/trees_test.dir/test/trees/trees_test.cc.s
.PHONY : test/trees/trees_test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... trees_test"
	@echo "... install/local"
	@echo "... test"
	@echo "... linkedlist_test"
	@echo "... main"
	@echo "... test_all"
	@echo "... rebuild_cache"
	@echo "... sort_test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/linkedlist/linkedlist_test.o"
	@echo "... test/linkedlist/linkedlist_test.i"
	@echo "... test/linkedlist/linkedlist_test.s"
	@echo "... test/sort/sort_test.o"
	@echo "... test/sort/sort_test.i"
	@echo "... test/sort/sort_test.s"
	@echo "... test/test_all.o"
	@echo "... test/test_all.i"
	@echo "... test/test_all.s"
	@echo "... test/trees/trees_test.o"
	@echo "... test/trees/trees_test.i"
	@echo "... test/trees/trees_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

